import { nanoid } from 'nanoid';
import { errors } from '../../utils/errors.js';
import { logger } from '../../utils/logger.js';
import { assertBranchName, isSafeBranchName } from '../../utils/repoIdentity.js';
import { getBranchHead } from '../github/repositories.js';
import { getFileContent } from '../github/contents.js';
import { commitFiles, createBranch, ensureFork, syncForkWithUpstream, uniqueBranchName } from '../github/writes.js';
import { createPullRequest } from '../github/pulls.js';
import { assertBaseUnchanged } from './patchValidator.js';

const SLUG_MAX = 42;

export function suggestBranchName(instruction) {
  const slug = String(instruction || 'ai change')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .split(/\s+/)
    .slice(0, 6)
    .join('-')
    .slice(0, SLUG_MAX)
    .replace(/^-+|-+$/g, '');
  return `codeweave/${slug || 'ai-change'}-${nanoid(6).toLowerCase().replace(/[^a-z0-9]/g, '')}`;
}

export function suggestCommitMessage(change) {
  const first = String(change.summary || change.instruction).split('\n')[0].trim();
  const subject = first.length > 68 ? `${first.slice(0, 65)}...` : first;
  return subject.charAt(0).toUpperCase() + subject.slice(1);
}

export function buildPullRequestBody(change, { viaFork, upstream }) {
  const fileList = change.files
    .map((f) => `- \`${f.path}\` (+${f.additions} / -${f.deletions})`)
    .join('\n');
  return [
    '## Summary',
    change.summary,
    '',
    '## Files changed',
    fileList,
    '',
    change.reasoning ? `## Why\n${change.reasoning}\n` : '',
    change.warnings?.length ? `## Review notes\n${change.warnings.map((w) => `- ${w}`).join('\n')}\n` : '',
    change.impactedSymbols?.length
      ? `## Callers to double-check\n${change.impactedSymbols.map((s) => `- \`${s}\``).join('\n')}\n`
      : '',
    '## Requested change',
    `> ${change.instruction}`,
    '',
    '---',
    viaFork
      ? `Generated by **CodeWeave** from a fork (no write access to \`${upstream}\`). Review before merging.`
      : 'Generated by **CodeWeave**. Review before merging.',
  ]
    .filter((part) => part !== '')
    .join('\n');
}

/**
 * Accept flow. Order matters and is enforced server-side:
 *   permissions -> (fork if needed) -> new branch -> re-verify base -> commit ->
 *   push -> pull request. The default branch is never a commit target.
 */
export async function applyChange({
  change,
  octokit,
  meta,
  viewerLogin,
  branchName,
  commitMessage,
  prTitle,
  prBody,
  createPr = true,
}) {
  if (change.status !== 'proposed') {
    throw errors.conflict(`This change is already ${change.status.replace('_', ' ')}.`);
  }
  if (!change.files.length) throw errors.patchFailed('This change has no file edits.');

  const viaFork = !meta.permissions.canWrite;
  let head = { owner: meta.owner, repo: meta.name, defaultBranch: meta.defaultBranch };

  if (viaFork) {
    if (meta.isPrivate) {
      throw errors.forbidden('This private repository cannot be forked with your current access.');
    }
    const fork = await ensureFork(octokit, { owner: meta.owner, repo: meta.name, viewerLogin });
    await syncForkWithUpstream(octokit, { owner: fork.owner, repo: fork.repo, branch: fork.defaultBranch });
    head = { owner: fork.owner, repo: fork.repo, defaultBranch: fork.defaultBranch, created: fork.created };
  }

  const requested = branchName && isSafeBranchName(branchName) ? branchName : suggestBranchName(change.instruction);
  if (requested === head.defaultBranch || requested === change.baseBranch) {
    throw errors.badRequest('Pick a branch name that is not the default branch.');
  }
  const branch = await uniqueBranchName(octokit, { owner: head.owner, repo: head.repo, branch: assertBranchName(requested) });

  // Forks share the upstream object store, so branching directly from the
  // reviewed upstream commit guarantees the patch applies to identical content.
  let baseSha = change.baseCommitSha;
  try {
    await createBranch(octokit, { owner: head.owner, repo: head.repo, branch, fromSha: baseSha });
  } catch (err) {
    if (!viaFork) throw err;
    const forkHead = await getBranchHead(octokit, head.owner, head.repo, head.defaultBranch);
    baseSha = forkHead.sha;
    await createBranch(octokit, { owner: head.owner, repo: head.repo, branch, fromSha: baseSha });
  }

  change.status = 'applying';
  change.headOwner = head.owner;
  change.headRepo = head.repo;
  change.headBranch = branch;
  change.viaFork = viaFork;
  await change.save();

  // Re-verify that every file still matches what the AI reviewed.
  for (const file of change.files) {
    if (file.action === 'create') continue;
    const current = await getFileContent(octokit, head.owner, head.repo, file.path, branch);
    assertBaseUnchanged({
      filePath: file.path,
      expectedSha: file.originalSha,
      currentSha: current.sha,
      expectedContent: file.originalContent,
      currentContent: current.content,
    });
  }

  const message = (commitMessage || suggestCommitMessage(change)).trim();
  const commit = await commitFiles(octokit, {
    owner: head.owner,
    repo: head.repo,
    branch,
    message,
    defaultBranch: head.defaultBranch,
    files: change.files.map((f) => ({ path: f.path, content: f.modifiedContent })),
  });

  change.status = 'committed';
  change.commitSha = commit.sha;
  change.commitMessage = message;
  change.appliedAt = new Date();
  change.statusMessage = `Committed ${change.files.length} file(s) to ${head.owner}/${head.repo}@${branch}`;
  await change.save();

  let pullRequest = null;
  if (createPr) {
    pullRequest = await createPullRequest(octokit, {
      owner: meta.owner,
      repo: meta.name,
      title: (prTitle || message).slice(0, 250),
      body: prBody || buildPullRequestBody(change, { viaFork, upstream: meta.fullName }),
      head: viaFork ? `${head.owner}:${branch}` : branch,
      base: change.baseBranch,
    });
    change.status = 'pr_open';
    change.pullRequestNumber = pullRequest.number;
    change.pullRequestUrl = pullRequest.url;
    change.statusMessage = `Pull request #${pullRequest.number} opened against ${meta.fullName}:${change.baseBranch}`;
    await change.save();
  }

  logger.info(
    {
      change: change._id.toString(),
      viaFork,
      head: `${head.owner}/${head.repo}:${branch}`,
      base: `${meta.fullName}:${change.baseBranch}`,
      pr: pullRequest?.number ?? null,
    },
    'AI change applied',
  );

  return { change, pullRequest, head, branch, commit, viaFork };
}
